sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
before_install:
  - docker build -t rishipahari/docker-springboot .
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-springboot"
  env: "DockerSpringboot-env"
  bucket_name: "elasticbeanstalk-eu-west-2-375731681245"
  bucket_path: "docker-springboot"
  on:
    branch: master
  access_key_id: $aws_key
  secret_access_key: $aws_secret